name: Devops project 2 

on :
  pull_request:
    branches: [ main ]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      with:
      node-version: 16.14
     - run: npm ci
     - run: npm test
     - run: npm run build
